# Generated by Django 5.2.3 on 2025-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_writer",
            field=models.BooleanField(default=False, verbose_name="Are you a writer?"),
        ),
    ]
