# Generated by Django 5.2.3 on 2025-07-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0002_alter_auditlog_id_category_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_free",
            field=models.BooleanField(default=True, verbose_name="Is free?"),
        ),
        migrations.AddField(
            model_name="article",
            name="is_standard",
            field=models.BooleanField(default=False, verbose_name="Is standard?"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Is premium?"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="Publish this article?"
            ),
        ),
    ]
